services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nexus-nginx-dev
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - client
  #     - server
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile.dev
    command: npm run dev -w @nexus/auth-service
    env_file:
      - ./apps/auth-service/.env.dev
    volumes:
      - .:/app
    ports:
      - "4001:4001"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: nexus-postgres-dev
    environment:
      POSTGRES_DB: nexus
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_password
    volumes:
      - ./packages/db/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: nexus-redis-dev
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    container_name: nexus-api-dev
    command: npm run dev -w @nexus/api
    env_file:
      - ./apps/api/.env.dev
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80" # expose on host
    volumes:
      - ./apps/api/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - api

  # client:
  #   build:
  #     context: ./apps/client
  #     dockerfile: Dockerfile.dev
  #   container_name: nexus-client-dev
  #   env_file:
  #     - ./apps/client/.env.dev
  #   volumes:
  #     - ./apps/client:/app
  #     - /app/node_modules
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - server

volumes:
  postgres_dev_data:
  nexus_node_modules:
